packages:
  - 'packages/**'
  - '.'
  - '!apps/**'

updateConfig:
  ignoreDependencies:
    - "@aws-sdk/signature-v4"
    - "@esbuild-kit/core-utils"
    - "@esbuild-kit/esm-loader"
    - "@humanwhocodes/config-array"
    - "@humanwhocodes/object-schema"
    - "@oclif/screen"
    - "@stylelint/postcss-css-in-js"
    - "glob@7.2.3"
    - "inflight"
    - "lex"
    - "mvdan-sh"
    - "node-domexception"
    - "rimraf@3.0.2"
    - "source-map@0.8.0-beta.0"
